
#' Download FLUXNET zip files
#'
#' Downloads zip files (one per site) for available FLUXNET sites.
#'
#' @param file_list_df When `NULL` (default), [flux_listall()] is used to
#'   determine the sites with data available to download (specific sites can be
#'   selected with `site_ids`).  If `file_list_df` is supplied, it should be a
#'   data frame generated by [flux_listall()], but potentially filtered to
#'   exlude some rows. This provides an alternative way of downloading only
#'   specific sites. See the examples for a possible use case. If `file_list_df`
#'   is not `NULL`, `cache_dir`, `use_cache`, and `cache_age` will be ingored
#'   but `site_ids` will still be used.
#' @param site_ids If `NULL` (default) all available sites will be downloaded.
#'   Alternatively, supply a character vector of site IDs. For example,
#'   `c("UK-GaB", "CA-Ca2")`.
#' @param download_dir The directory to download zip files to.
#' @param overwrite Logical; overwrite already downloaded .zip files? If `FALSE`
#'   it will skip downloading existing files, unless they are invalid .zip files
#'   (e.g. due to partial download or corruption).
#' @param user_info An optional list with data-hub-specific user information.
#'   Only AmeriFlux uses this currently. By default, these are retrieved from
#'   environment variables by [flux_amf_credentials()].
#' @param ... Arguments passed to [flux_listall()].
#'
#' @returns Invisibly returns a tibble with the download URL, path on disk, HTTP
#'   status code, and whether or not the download was successful.
#' @examples
#' \dontrun{
#' # Download data for all available sites
#' flux_download()
#'
#' # Download data for just select site IDs
#' flux_download(site_ids = c("UK-GaB", "CA-Ca2"))
#'
#' # Download specific sites filtered by site metadata (IGPB  and data hub for example)
#' available_sites <- flux_listall()
#' to_get <-
#'   available_sites[available_sites$igbp == "CRO" & available_sites$data_hub == "AmeriFlux", ]
#' flux_download(file_list_df = to_get)
#'
#' # Get a fresh list of available data and overwrite any existing downloads
#' flux_download(use_cache = FALSE, overwrite = FALSE)
#' }
#'
#' @export
flux_download <- function(
  file_list_df = NULL,
  site_ids = NULL,
  download_dir = "fluxnet",
  overwrite = FALSE,
  user_info = list(ameriflux = flux_amf_credentials()),
  ...
) {
  if (!is.null(site_ids)) {
    if (any(site_ids == "all")) {
      lifecycle::deprecate_warn(
        "0.3.1",
        "flux_read(site_ids = 'can no longer be set to \"all\"')",
        details = "Using `site_ids = NULL`"
      )
      site_ids <- NULL
    }
  }
  file_list_null <- is.null(file_list_df)
  if (!is.null(file_list_df)) {
    if (!is.data.frame(file_list_df)) {
      cli::cli_abort(
        "{.var file_list_df} must be of class {.cls data.frame}, not {.cls {class(file_list_df)}}!"
      )
    }
  } else {
    file_list_df <- flux_listall(...)
  }

  if (is.null(site_ids)) {
    if (file_list_null) {
      cli::cli_inform("Downloading data from all sites in {.arg file_list_df}.")
    } else {
      cli::cli_inform("Downloading data from all available sites.")
    }
  } else {
    cli::cli_inform("Downloading data from specified sites.")
  }

  fs::dir_create(download_dir)

  # Check for existing files unless overwrite = TRUE
  if (isFALSE(overwrite)) {
    existing_paths <- fs::dir_ls(download_dir, glob = "*.zip")
    existing_files <- existing_paths %>% fs::path_file()

    existing_valid_files <- existing_files[purrr::map_lgl(
      existing_paths,
      check_zip
    )]

    file_list_df <- file_list_df %>%
      dplyr::filter(!.data$fluxnet_product_name %in% existing_valid_files)
  }

  # check that there are rows left after filtering
  if (nrow(file_list_df) == 0) {
    cli::cli_warn(
      "No files to download! Check that {.arg site_ids} are correct or that files aren't already downloaded if {.arg overwrite = FALSE}."
    )
    return(invisible(NULL))
  }

  file_list <- withr::local_tempfile()
  readr::write_csv(file_list_df, file_list)

  fluxnet_py <- reticulate::import("fluxnet_shuttle")
  dl <- fluxnet_py$download(
    site_ids = as.list(site_ids),
    snapshot_file = file_list,
    output_dir = download_dir,
    user_info = user_info
  )
  out <- dplyr::tibble(
    download_path = dl,
  )
  return(invisible(out))
}


check_zip <- function(zip_file) {
  test <- try(utils::unzip(zip_file, list = TRUE), silent = TRUE)
  if (inherits(test, "try-error")) {
    return(FALSE)
  } else {
    return(TRUE)
  }
}
